# Generated by Django 5.2.16 on 2026-07-27 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(default='임재혁', max_length=100)),
                ('name_en', models.CharField(default='jaehyeok Lim', max_length=100)),
                ('role_ko', models.CharField(default='임베디드 소프트웨어 엔지니어', max_length=150)),
                ('role_en', models.CharField(default='Embedded Software Engineer', max_length=150)),
                ('tagline_ko', models.CharField(blank=True, max_length=200)),
                ('tagline_en', models.CharField(blank=True, max_length=200)),
                ('bio_ko', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '기술 카테고리',
                'verbose_name_plural': '기술 카테고리',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work', '경력'), ('education', '학력')], default='work', max_length=20)),
                ('title_ko', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_ko', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='비워두면 "현재"로 표시됩니다.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='숫자가 작을수록 먼저 표시됩니다.')),
            ],
            options={
                'verbose_name': '타임라인 항목',
                'verbose_name_plural': '타임라인 항목',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.skillcategory')),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술',
                'ordering': ['order', 'name'],
            },
        ),
    ]
