# Generated by Django 5.2.16 on 2026-07-27 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ko', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary_ko', models.CharField(help_text='목록 카드에 보일 한 줄 요약', max_length=300)),
                ('summary_en', models.CharField(max_length=300)),
                ('overview_ko', models.TextField(help_text='개요')),
                ('overview_en', models.TextField()),
                ('role_ko', models.TextField(help_text='본인 역할 / 담당 범위')),
                ('role_en', models.TextField()),
                ('architecture_ko', models.TextField(blank=True, help_text='시스템 구조/아키텍처 설명')),
                ('architecture_en', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='비워두면 "진행중"으로 표시됩니다.', null=True)),
                ('tech_stack', models.CharField(help_text='쉼표로 구분 (예: C, FreeRTOS, STM32, CAN)', max_length=400)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('architecture_diagram', models.ImageField(blank=True, null=True, upload_to='projects/diagrams/')),
                ('visibility', models.CharField(choices=[('full', '전체 공개'), ('abstracted', '추상화하여 공개')], default='full', help_text='추상화 공개 선택 시, 회사명·제품명 등 민감 정보는 제목/본문에서 직접 가려서 작성하세요.', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='숫자가 작을수록 먼저 표시됩니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', '이미지'), ('video', '동영상')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/media/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube 등 외부 동영상 링크')),
                ('caption_ko', models.CharField(blank=True, max_length=200)),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='projects.project')),
            ],
            options={
                'verbose_name': '프로젝트 첨부',
                'verbose_name_plural': '프로젝트 첨부',
                'ordering': ['order'],
            },
        ),
    ]
